- name: Setup development environment
  hosts: localhost
  become: true
  vars_files:
    - secrets.yml
  roles:
    - role: darkwizard242.go
      vars:
        go_version: "1.20"
        go_setup: true
    - role: geerlingguy.docker
      vars:
        docker_install_compose_plugin: true
  tasks:
    - name: Set system locales
      ansible.builtin.import_tasks: tasks/locales-setup.ansible.yml
      vars:
        locales: [
          'en_US.UTF-8 UTF-8'
        ]
    - name: Install ansible lint
      ansible.builtin.import_tasks: tasks/ansible-lint-install.ansible.yml
    - name: Install Terraform
      ansible.builtin.import_tasks: tasks/terraform-install.ansible.yml
    - name: Setup Bash aliases
      ansible.builtin.import_tasks: tasks/aliases-setup.ansible.yml
    - name: Install GO tools
      ansible.builtin.import_tasks: tasks/go-tools.ansible.yml
    - name: Install VSCode extensions
      ansible.builtin.import_tasks: tasks/vscode-setup.ansible.yml
      vars:
        vscode_extensions: [
          'tomoki1207.pdf',
          'golang.go',
          'hashicorp.terraform',
          'ms-azuretools.vscode-docker',
          'oderwat.indent-rainbow',
          'jock.svg',
          'yzhang.markdown-all-in-one',
          'davidanson.vscode-markdownlint',
          'gruntfuggly.todo-tree',
          'maxvanderschee.web-accessibility',
          'usernamehw.errorlens',
          'vivaxy.vscode-conventional-commits',
          'jeff-hykin.polacode-2019',
          'zokugun.explicit-folding',
          'hangxingliu.vscode-systemd-support',
          'streetsidesoftware.code-spell-checker',
          'wix.vscode-import-cost',
          '42crunch.vscode-openapi',
          'gurumukhi.selected-lines-count',
          'redhat.ansible',
          'jeremyfunk.hidefiles',
          'hediet.vscode-drawio',
          'george-alisson.html-preview-vscode'
        ]
