---
- name: Setup development environment
  hosts: localhost
  become: true
  vars_files:
    - secrets.yml
  tasks:
    - name: Setup oh-my-zsh
      ansible.builtin.import_tasks:
        file: ansible/oh_my_zsh/tasks/main.ansible.yml
      vars:
        oh_my_zsh_users: "{{ local_users }}"
        oh_my_zsh_theme: robbyrussell
        oh_my_zsh_plugins:
          - docker
          - docker-compose
          - git
          - terraform
          - vscode
        oh_my_zsh_exports:
          - name: PATH
            value: $PATH:/usr/local/go/bin
        oh_my_zsh_aliases:
          - name: tf
            command: terraform
          - name: tfc
            command: terraform apply
          - name: tfcal
            command: terraform apply --auto-approve
          - name: tfd
            command: terraform destroy
          - name: tfdal
            command: terraform destroy --auto-approve
          - name: tfi
            command: terraform init
          - name:
              - tfp
              - tfplan
            command: terraform plan
          - name:
              - tfr
              - tfrefresh
            command: terraform refresh
          - name:
              - tfs
              - tfshow
            command: terraform show
          - name: tfdebug
            command: export "TF_LOG"=DEBUG
          - name: tftrace
            command: export "TF_LOG"=TRACE
          - name: tfwarn
            command: export "TF_LOG"=WARN
          - name: tfinfo
            command: export "TF_LOG"=INFO
          - name:
              - gc
              - gitc
            command: git clone
          - name:
              - goc
              - goclean
            command: go clean -testcache
          - name:
              - gocover
              - gocoverage
            command: go test -coverprofile=_coverage.out ./...&&go tool cover -html=_coverage.out -o _coverage.html
          - name:
              - gomodtidy
              - gomodt
              - gomt
              - gmt
            command: go mod tidy
          - name: x
            command: export
    - name: Set system locales
      ansible.builtin.import_tasks:
        file: ansible/locales/tasks/main.ansible.yml
      vars:
        locales:
          - "en_US.UTF-8 UTF-8"
    - name: Install ansible lint
      ansible.builtin.import_tasks:
        file: ansible/ansible_lint/tasks/main.ansible.yml
    - name: Install inkscape
      ansible.builtin.apt:
        name: inkscape
        state: present
        cache_valid_time: 900
    - name: Install influxdb2-client
      ansible.builtin.import_tasks:
        file: ansible/influxdb/tasks/main.ansible.yml
    - name: Install Docker
      ansible.builtin.include_role:
        name: geerlingguy.docker
      vars:
        docker_install_compose_plugin: true
        docker_users: "{{ local_users }}"
    - name: Install Terraform
      ansible.builtin.import_tasks:
        file: ansible/terraform/tasks/main.ansible.yml
    - name: Install GO
      ansible.builtin.include_role:
        name: tinyblargon.go
      vars:
        go_version: "1.24.1"
        go_checksum: sha256:cb2396bae64183cdccf81a9a6df0aea3bce9511fc21469fb89a0c00470088073
    - name: Install GO tools
      ansible.builtin.import_tasks:
        file: ansible/go_tools/tasks/main.ansible.yml
      vars:
        go_path: "/usr/local/go"
    - name: Install VSCode extensions
      ansible.builtin.import_tasks:
        file: ansible/vscode/tasks/main.ansible.yml
      vars:
        vscode_machine_config: >-
          {{ lookup('file', './vscode/server/machine.json') }}
        vscode_workspaces:
          - path: "~"
            config: >-
              {{ lookup('file', './vscode/server/workspace-home.json') }}
        vscode_extensions:
          - redhat.ansible
          - mads-hartmann.bash-ide-vscode
          - alefragnani.bookmarks
          - streetsidesoftware.code-spell-checker
          - github.copilot
          - usernamehw.errorlens
          - zokugun.explicit-folding
          - golang.go
          - eamodio.gitlens
          - george-alisson.html-preview-vscode
          - jeremyfunk.hidefiles
          - oderwat.indent-rainbow
          - meezilla.json
          - samuelcolvin.jinjahtml
          - jeff-hykin.polacode-2019
          - esbenp.prettier-vscode
          - gurumukhi.selected-lines-count
          - tyriar.sort-lines
          - jock.svg
          - hashicorp.terraform
          - gruntfuggly.todo-tree
          - leonardssh.vscord
          - vivaxy.vscode-conventional-commits
          - ms-azuretools.vscode-docker
          - hediet.vscode-drawio
          - 42crunch.vscode-openapi
          - davidanson.vscode-markdownlint
          - hangxingliu.vscode-systemd-support
          - ahmadalli.vscode-nginx-conf
          - yandeu.five-server
          - wix.vscode-import-cost
