---
- name: Setup development environment
  hosts: localhost
  become: true
  vars_files:
    - secrets.yml
  roles:
    - role: darkwizard242.go
      vars:
        go_version: "1.21.0"
        go_setup: true
    - role: geerlingguy.docker
      vars:
        docker_install_compose_plugin: true
        docker_users: "{{ local_users }}"
  tasks:
    - name: Setup oh-my-zsh
      ansible.builtin.import_tasks: tasks/oh-my-zsh.ansible.yml
      vars:
        oh_my_zsh_users: "{{ local_users }}"
        oh_my_zsh_theme: robbyrussell
        oh_my_zsh_plugins:
          - git
        oh_my_zsh_aliases:
          - name: tf
            command: terraform
          - name: tfc
            command: terraform apply
          - name: tfcal
            command: terraform apply --auto-approve
          - name: tfd
            command: terraform destroy
          - name: tfdal
            command: terraform destroy --auto-approve
          - name: tfi
            command: terraform init
          - name: tfp
            command: terraform plan
          - name: tfdebug
            command: export "TF_LOG"=DEBUG
          - name: tftrace
            command: export "TF_LOG"=TRACE
          - name: tfwarn
            command: export "TF_LOG"=WARN
          - name: tfinfo
            command: export "TF_LOG"=INFO
          - name: goc
            command: go clean -testcache
          - name: staticcheck
            command: ~/go/bin/staticcheck
    - name: Set system locales
      ansible.builtin.import_tasks: tasks/locales-setup.ansible.yml
      vars:
        locales: [
          'en_US.UTF-8 UTF-8'
        ]
    - name: Install ansible lint
      ansible.builtin.import_tasks: tasks/ansible-lint-install.ansible.yml
    - name: Install inkscape
      ansible.builtin.apt:
        name: inkscape
        state: present
        cache_valid_time: 900
    - name: Install Terraform
      ansible.builtin.import_tasks: tasks/terraform-install.ansible.yml
    - name: Install GO tools
      ansible.builtin.import_tasks: tasks/go-tools.ansible.yml
    - name: Install VSCode extensions
      ansible.builtin.import_tasks: tasks/vscode-setup.ansible.yml
      vars:
        vscode_extensions: [
          'golang.go',
          'hashicorp.terraform',
          'ms-azuretools.vscode-docker',
          'oderwat.indent-rainbow',
          'jock.svg',
          'yzhang.markdown-all-in-one',
          'davidanson.vscode-markdownlint',
          'gruntfuggly.todo-tree',
          'maxvanderschee.web-accessibility',
          'usernamehw.errorlens',
          'vivaxy.vscode-conventional-commits',
          'jeff-hykin.polacode-2019',
          'zokugun.explicit-folding',
          'hangxingliu.vscode-systemd-support',
          'streetsidesoftware.code-spell-checker',
          'wix.vscode-import-cost',
          '42crunch.vscode-openapi',
          'gurumukhi.selected-lines-count',
          'redhat.ansible',
          'jeremyfunk.hidefiles',
          'hediet.vscode-drawio',
          'samuelcolvin.jinjahtml',
          'mads-hartmann.bash-ide-vscode',
          'leonardssh.vscord',
          'ahmadalli.vscode-nginx-conf',
          'tyriar.sort-lines',
          'george-alisson.html-preview-vscode'
        ]
