---
- name: Update apt and install javascript applications
  ansible.builtin.apt:
    name:
      - nodejs
      - npm
  register: apt_action
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

- name: Install "vue cli" node.js package globally.
  community.general.npm:
    name: "@vue/cli"
    global: true
    state: latest
