- name: Install pip3
  ansible.builtin.apt:
    name: python3-pip
    state: latest
    update_cache: true
    cache_valid_time: 900
  when: >
    ansible_distribution == 'Debian'
    or
    ansible_distribution == 'Ubuntu'
  register: apt_action
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

- name: Install ansible_lint
  ansible.builtin.pip:
    name: "ansible-lint"
    state: present
