---
- name: Install ansible-lint
  ansible.builtin.apt:
    name: ansible-lint
    update_cache: true
    cache_valid_time: 900
  when: >
    ansible_distribution == 'Debian'
    or
    ansible_distribution == 'Ubuntu'
  register: apt_action
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)
