- name: Update apt and install dependencies for delv debugger
  apt:
    name=gcc
    state=latest
    update_cache=yes
  register: apt_action
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

- name: Install go modules
  become: false
  shell: "go install {{ item }}"
  loop: [
    '-v github.com/go-delve/delve/cmd/dlv@latest',
    '-v golang.org/x/tools/cmd/goimports@latest',
    'honnef.co/go/tools/cmd/staticcheck@latest',
    'golang.org/x/tools/gopls@latest'
  ]