---
- name: Update apt and install dependencies for delv debugger
  ansible.builtin.apt:
    name: gcc
    cache_valid_time: 900
  register: apt_action
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

- name: Get go path
  ansible.builtin.set_fact:
    go_path_tmp: "{{ go_path | default(lookup('env', 'GOPATH')) + '/bin/go' }}"

- name: Install go modules
  become: false
  ansible.builtin.command: "{{ go_path_tmp }} install {{ item }}"
  loop: [
    'github.com/go-delve/delve/cmd/dlv@latest',
    'golang.org/x/tools/cmd/goimports@latest',
    'honnef.co/go/tools/cmd/staticcheck@latest',
    'golang.org/x/tools/gopls@latest'
  ]
  register: go_install
  when: go_path != "/bin/go"
  changed_when: go_install.stderr != ""
