- name: Update apt and install javascript applications
  apt:
    name={{ item }}
    state=latest
    update_cache=yes
  loop: [ 'nodejs', 'npm']
  register: apt_action
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

- name: Install "vue cli" node.js package globally.
  npm:
    name: '@vue/cli'
    global: yes
    state: latest