---
- name: Copy vscode-server settings
  become: false
  ansible.builtin.copy:
    content: "{{ vscode_machine_config }}"
    dest: ~/.vscode-server/data/Machine/settings.json
    mode: "0644"

- name: Create .vscode directory
  become: false
  ansible.builtin.file:
    path: "{{ item.path }}/.vscode"
    state: directory
    mode: "0755"
  loop: "{{ vscode_workpaces | default([]) }}"
  loop_control:
    label: "{{ item }}"

- name: Copy vscode-server settings
  become: false
  ansible.builtin.copy:
    content: "{{ item.config }}"
    dest: "{{ item.path }}/.vscode/settings.json"
    mode: "0644"
  loop: "{{ vscode_workspaces | default([]) }}"
  loop_control:
    label: "{{ item }}"

- name: Find VScode path
  become: false
  ansible.builtin.command: "/usr/bin/which code"
  register: which_output
  changed_when: false

- name: Set VScode Location
  ansible.builtin.set_fact:
    vscode_location: "{{ which_output.stdout }}"

- name: Show vscode path
  ansible.builtin.debug:
    msg: "{{ vscode_location }}"

- name: Install VScode extensions
  become: false
  ansible.builtin.command: "{{ vscode_location }} --install-extension {{ item }}"
  loop: "{{ vscode_extensions }}"
  register: vscode_extensions_output
  changed_when: >-
    "is already installed."
    not in vscode_extensions_output.stdout
  failed_when: >-
    "\nCannot install the"
    in vscode_extensions_output.stdout
  when: vscode_extensions is defined
