- name: Start vscode on login
  become: false
  ansible.builtin.lineinfile:
    state: present
    path: ~/.profile
    line: 'code ~'

- name: Copy vscode-server settings
  become: false
  ansible.builtin.copy:
    src: ../files/vscode-server/machine.json
    dest: ~/.vscode-server/data/Machine/settings.json

- name: Create .vscode directory
  become: false
  ansible.builtin.file:
    path: ~/.vscode
    state: directory
    mode: 0755

- name: Copy vscode-server settings
  become: false
  ansible.builtin.copy:
    src: ../files/vscode-server/workspace-home.json
    dest: ~/.vscode/settings.json

- name: Find VScode path
  become: false
  ansible.builtin.command: "/usr/bin/which code"
  register: which_output

- name: Set VScode Location
  ansible.builtin.set_fact:
    vscode_location: "{{ which_output.stdout }}"

- name: Show vscode path
  ansible.builtin.debug:
    msg: "{{ vscode_location }}"

- name: Install VScode extensions
  become: false
  ansible.builtin.command: "{{ vscode_location }} --install-extension {{ item }}"
  loop: "{{ vscode_extensions }}"
