- name: Uninstall docker-compose-plugin
  apt: name=docker-compose-plugin state=absent
  register: apt_action
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)
  when: >
    (ansible_distribution == 'Debian'
    or
    ansible_distribution == 'Ubuntu')