- name: Stop and disable docker service
  ansible.builtin.service:
    name: docker
    state: stopped
    enabled: false
  register: service_action
  until: service_action is success or ('Unable to start service docker' not in service_action.msg)

- include_tasks: "uninstall-compose.yml"

- name: Uninstall Docker
  apt:
    name={{ item }}
    state=absent
  loop: [ 'docker-ce', 'docker-ce-cli', 'containerd.io']
  register: apt_action
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

- name: Remove Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable
    state: absent

- name: Remove Docker GPG apt Key
  apt_key:
    id: 0EBFCD88
    state: absent

- debug: msg="Not removing [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg', 'lsb-release'] removing these packages can have unintended side effects."

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes