---
- name: Update apt and install dependencies for delv debugger
  ansible.builtin.apt:
    name: gcc
    cache_valid_time: 900
  register: apt_action
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

- name: Install go modules
  ansible.builtin.command:
    cmd: >-
      {{ go_root_used + '/bin/go' }} install {{ item.name + go_item_version }}
  loop: "{{ go_modules }}"
  loop_control:
    label: "{{ item.name }}"
  environment:
    GOROOT: "{{ go_root_used }}"
  vars:
    go_root_used: "{{ go_root | default(lookup('env', 'GOROOT')) }}"
    go_item_version: >-
      {{ '' if '@' in item.name else
        ('@' + (item.version
          if item.version is defined and item.version != '' else 'latest')) }}
  register: go_install
  when: go_root != "/bin/go"
  changed_when: (go_install.stderr_lines
    | reject('search', ' requires go >= ') | list | length) > 0
